# Generated by Django 5.2.7 on 2025-11-04 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_mockup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockup',
            name='image',
        ),
        migrations.AddField(
            model_name='dress',
            name='mockup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.mockup'),
        ),
    ]
